### ISSUE TITLE
qUmap error with HGNC.lookup

### ISSUE THREAD

**Issue by Chongram** [vertesy/Seurat.utils#58] opened 2022-02-07 17:30 UTC
```r
> qUMAP(feature = "CNTNAP2", obj = combined.obj)
Error in check.genes(feature, verbose = F, HGNC.lookup = HGNC.lookup,  : 
  unused arguments (verbose = F, HGNC.lookup = HGNC.lookup, makeuppercase = make.uppercase)

```

**Comment by vertesy** [comment] 2022-02-07 18:11
Unclear why this arises. Works on my end without a bug, so cannot reproduce.

I think it may be incompatibilty due to specific versions installed. I did some updates that make this less likely to occur.

As it works with the installed code on your end I close this

**Closed by vertesy** 2022-02-07 18:11 UTC
Labels: bug
